export const WORKFLOW_PRIMARY_FILE = "AGENTS.md";
export const LEGACY_WORKFLOW_FILE = "CLAUDE.md";

export const LEGACY_CLAUDE_SYMLINK_TARGET = WORKFLOW_PRIMARY_FILE;
export const LEGACY_AGENTS_SYMLINK_TARGET = LEGACY_WORKFLOW_FILE;
