export const WORKFLOW_PRIMARY_FILE = "AGENTS.md";
export const WORKFLOW_COMPAT_FILE = "CLAUDE.md";

export const WORKFLOW_COMPAT_SYMLINK_TARGET = WORKFLOW_PRIMARY_FILE;
export const LEGACY_AGENTS_SYMLINK_TARGET = WORKFLOW_COMPAT_FILE;
